model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
dataset: identity,ruozhiba
template: llama3
cutoff_len: 2048
max_samples: 200
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: /home/ubuntu/finetuned_model
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
warmup_steps: 10
